// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220727083411_seedActivity")]
    partial class seedActivity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("Domain.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f17e3f20-c85c-4aaf-8412-89ae0069ce48"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2022, 5, 27, 16, 34, 11, 29, DateTimeKind.Local).AddTicks(7280),
                            Description = "Activity 2 months ago",
                            Title = "Past Activity 1",
                            Venue = "Pub"
                        },
                        new
                        {
                            Id = new Guid("9b11a4ea-a585-4e8f-b6be-6cbb5607118e"),
                            Category = "culture",
                            City = "Paris",
                            Date = new DateTime(2022, 6, 27, 16, 34, 11, 29, DateTimeKind.Local).AddTicks(7297),
                            Description = "Activity 1 month ago",
                            Title = "Past Activity 2",
                            Venue = "Louvre"
                        },
                        new
                        {
                            Id = new Guid("677b012f-a342-4f2c-af21-a1dc8d6635f2"),
                            Category = "culture",
                            City = "London",
                            Date = new DateTime(2022, 8, 27, 16, 34, 11, 29, DateTimeKind.Local).AddTicks(7299),
                            Description = "Activity 1 month in future",
                            Title = "Future Activity 1",
                            Venue = "Natural History Museum"
                        },
                        new
                        {
                            Id = new Guid("d5c3b51d-1b2c-4f4c-9c2a-d0efa00b1c2a"),
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2022, 9, 27, 16, 34, 11, 29, DateTimeKind.Local).AddTicks(7301),
                            Description = "Activity 2 months in future",
                            Title = "Future Activity 2",
                            Venue = "O2 Arena"
                        },
                        new
                        {
                            Id = new Guid("e559e647-5bc8-4862-86a2-37486afc1303"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2022, 10, 27, 16, 34, 11, 29, DateTimeKind.Local).AddTicks(7303),
                            Description = "Activity 3 months in future",
                            Title = "Future Activity 3",
                            Venue = "Another pub"
                        },
                        new
                        {
                            Id = new Guid("62368b65-8f93-475f-82ae-a7c54cf69dfd"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2022, 11, 27, 16, 34, 11, 29, DateTimeKind.Local).AddTicks(7305),
                            Description = "Activity 4 months in future",
                            Title = "Future Activity 4",
                            Venue = "Yet another pub"
                        },
                        new
                        {
                            Id = new Guid("e91f1cf2-6cf6-4046-93e7-fb343f0d14ae"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2022, 12, 27, 16, 34, 11, 29, DateTimeKind.Local).AddTicks(7318),
                            Description = "Activity 5 months in future",
                            Title = "Future Activity 5",
                            Venue = "Just another pub"
                        },
                        new
                        {
                            Id = new Guid("5377de01-48ff-463f-afd0-7944b152b3c6"),
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2023, 1, 27, 16, 34, 11, 29, DateTimeKind.Local).AddTicks(7320),
                            Description = "Activity 6 months in future",
                            Title = "Future Activity 6",
                            Venue = "Roundhouse Camden"
                        },
                        new
                        {
                            Id = new Guid("bd9b90c5-ad33-4663-9b5f-f28990f61a3e"),
                            Category = "travel",
                            City = "London",
                            Date = new DateTime(2023, 2, 27, 16, 34, 11, 29, DateTimeKind.Local).AddTicks(7322),
                            Description = "Activity 2 months ago",
                            Title = "Future Activity 7",
                            Venue = "Somewhere on the Thames"
                        },
                        new
                        {
                            Id = new Guid("be4ab50f-cab6-4607-a206-f15e0b4626c6"),
                            Category = "film",
                            City = "London",
                            Date = new DateTime(2023, 3, 27, 16, 34, 11, 29, DateTimeKind.Local).AddTicks(7324),
                            Description = "Activity 8 months in future",
                            Title = "Future Activity 8",
                            Venue = "Cinema"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
